# Site settings
title: Devlucky
email: devluucky@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A bunch of colleagues writing about swift, javascript, ruby, go, algorithms, performance and coding stories
baseurl: ""
assets-path: "/assets/"
images-path: "/assets/images/"
permalink: "/:title"
url: "http://devlucky.github.io"
twitter_username: devluckyness
github_username:  devlucky
medium_username: devlucky
projects: 
  - name: Kakapo.js 
    link: kakapo-js
    header_img: js-bg.jpg
    logo: kakapo.gif
    description: The next level mocking framework, discover a new way of declare http mocks, directly in your browser.
                 Kakapo.js gives you a set of utilities to exactly recreate your real backend.
  - name: Kakapo Swift 
    link: kakapo-swift
    header_img: swift-bg.jpg
    logo: kakapo.gif
    description: Lorem ipsum Dolore culpa cillum non dolor sit nulla eu est anim non non minim dolor incididunt dolor ut ullamco sint aliqua dolore sed ut ex occaecat Ut aliquip Duis adipisicing non irure cupidatat proident dolore occaecat fugiat sunt cupidatat dolore.
team: 
  - name: Hector
    twitter: zzarcon
    avatar: hector-picture.jpeg
  - name: Joan 
    twitter: joanromano
    avatar: joan-picture.jpeg
  - name: Alex
    twitter: ManzoPower
    avatar: alex-picture.png
  - name: Oskar
    twitter: rpunkfu
    avatar: oskar-picture.jpg
  - name: Yohan 
    twitter: groyoh
    avatar: yohan-picture.jpg

# Build settings
markdown: kramdown
exclude:
  - node_modules