# Site settings
title: Devlucky
email: devluucky@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A bunch of colleagues writing about swift, javascript, ruby, go, algorithms, performance and coding stories
baseurl: ""
assets-path: "/assets/"
images-path: "/assets/images/"
permalink: "/:title"
url: "http://devlucky.github.io"

twitter_username: devluckyness
github_username:  devlucky
medium_username: devlucky

# Build settings
markdown: kramdown
exclude:
  - node_modules